### ISSUE TITLE
viz: Disable profiling support for now

### ISSUE THREAD

**Issue by jpsamaroo** [mrufsvold/Waluigi.jl#10]
Dagger's profiling support is currently poorly tested because Julia's profiler doesn't have an interface that best supports how we want to use the profiler. It also has very high overhead and will either over- or under-report profile stacks for Dagger tasks. I would recommend disabling it or making it opt-in for now.

**Comment by mrufsvold** [comment]
Thanks for the catch! I haven't worked out how I want to allow customization of the vizualization yet, so I'll just take it out for now.
