### ISSUE TITLE
Replace DataFrames and Parquet2 in test env

### ISSUE THREAD

**Issue by mrufsvold** [mrufsvold/Waluigi.jl#14]
Right now, I'm using a custom target that saves off to Parquet2. I wrote it as an example for myself on how a Table.jl target might look. But precompiling those dependencies reeeeally slows down testing. Coming up with a lighter weight test of a custom target would really help development. 

All we need is a custom target defined and `is_complete`, `store`, and `retrieve` all defined for that type. I don't particularly care what it uses as long as it's fast :) Could just be something that writes strings to a text file.

**Comment by Yettimania** [comment]
PR: https://github.com/mrufsvold/Waluigi.jl/pull/18
